# Generated by Django 3.1.5 on 2021-02-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
    ]
