# Generated by Django 3.1.5 on 2021-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, verbose_name='이름')),
                ('password', models.CharField(max_length=30, verbose_name='비밀번호')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('user_level', models.CharField(choices=[('normal_user', '일반사용자'), ('admin', '관리자')], max_length=30, verbose_name='사용자 권한')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'blog_user',
            },
        ),
    ]
