# Generated by Django 3.1.6 on 2021-02-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
